# Generated by Django 3.2.25 on 2024-09-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='image',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
