# Generated by Django 3.2.25 on 2024-09-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_info',
            name='emp_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
