# Generated by Django 3.2.25 on 2024-09-24 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_employee_info_emp_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='image',
            new_name='employee_image',
        ),
    ]
