# Generated by Django 3.2.25 on 2024-10-03 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_image_employee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction_image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee_info')),
            ],
        ),
    ]
